name: Publish JupyterBook to GitHub Pages

on:
  push: # trigger build only when push to master
    branches:
      - master
      - feature/* #adding feature for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+git://github.com/executablebookproject/cli.git#egg=master
          python -m pip install datascience
          python -m pip install ghp-import
          PATH="${PATH}:${HOME}/.local/bin"

      - name: Build book TOC file
        run: |
          jupyter-book toc ./content

      - name: Build book HTML
        run: |
          jupyter-book build ./content

      - name: Deploy yo GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./content/_build/html
          commit_message: ${{github.event.head_commit.message}}
